BLOG_CATEGORIES = [
  { "id": 1, "topic": "Technology", "description": "Latest trends and updates in technology" },
  { "id": 2, "topic": "Health", "description": "Health tips and wellness advice" },
  { "id": 3, "topic": "Travel", "description": "Travel guides and destination reviews" },
  { "id": 4, "topic": "Food", "description": "Recipes and culinary experiences" },
  { "id": 5, "topic": "Lifestyle", "description": "Lifestyle tips and personal development" },
  { "id": 6, "topic": "Finance", "description": "Financial advice and investment tips" },
  { "id": 7, "topic": "Education", "description": "Educational resources and learning tips" },
  { "id": 8, "topic": "Entertainment", "description": "Movies, music, and pop culture" },
  { "id": 9, "topic": "Sports", "description": "Sports news and analysis" },
  { "id": 10, "topic": "Fashion", "description": "Fashion trends and style tips" },
  { "id": 11, "topic": "Parenting", "description": "Parenting tips and family advice" },
  { "id": 12, "topic": "Environment", "description": "Sustainability and environmental issues" },
  { "id": 13, "topic": "Politics", "description": "Political news and analysis" },
  { "id": 14, "topic": "Science", "description": "Scientific discoveries and research" },
  { "id": 15, "topic": "Art", "description": "Artistic expression and creativity" },
  { "id": 16, "topic": "History", "description": "Historical events and analysis" },
  { "id": 17, "topic": "Automotive", "description": "Car reviews and automotive news" },
  { "id": 18, "topic": "Gaming", "description": "Video game news and reviews" },
  { "id": 19, "topic": "Real Estate", "description": "Real estate market trends and tips" },
  { "id": 20, "topic": "Pets", "description": "Pet care and animal welfare" },
  { "id": 21, "topic": "DIY", "description": "Do-it-yourself projects and home improvement" },
  { "id": 22, "topic": "Relationships", "description": "Relationship advice and personal stories" },
  { "id": 23, "topic": "Cryptocurrency", "description": "Cryptocurrency news and investment tips" },
  { "id": 24, "topic": "Mental Health", "description": "Mental health awareness and support" },
  { "id": 25, "topic": "Social Media", "description": "Social media trends and tips" },
  { "id": 26, "topic": "Photography", "description": "Photography tips and techniques" }
]
